# Generated by Django 2.0.6 on 2018-06-18 15:43

from django.db import migrations, models
import skbrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('skbrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=skbrest.models.User.upload_to),
        ),
    ]
