# Generated by Django 2.0.7 on 2018-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20180707_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='render_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('VT', 'Vocabulary Test')], default='MC', max_length=2),
            preserve_default=False,
        ),
    ]
