# Generated by Django 2.0.5 on 2018-05-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skbrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.TextField(default='mname'),
            preserve_default=False,
        ),
    ]
