# Generated by Django 2.0.6 on 2018-06-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skbrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Anouncement',
                'verbose_name_plural': 'Anouncements',
            },
        ),
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matter', models.CharField(choices=[('PRESENTATION', 'Presentation'), ('HOMEWORK', 'Homework'), ('EXAM', 'Exam')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'moderator',
                'verbose_name_plural': 'moderators',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uploaded', models.DateTimeField()),
                ('effective_from', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('size', models.FloatField()),
                ('content', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='skbrest.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='isEmailActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isEmailActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skbrest.Course'),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skbrest.Course'),
        ),
        migrations.AddField(
            model_name='anouncement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skbrest.Moderator'),
        ),
    ]
