# Generated by Django 2.0.6 on 2018-06-18 16:10

from django.db import migrations, models
import skbrest.models


class Migration(migrations.Migration):

    dependencies = [
        ('skbrest', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='image',
            field=models.ImageField(blank=True, upload_to=skbrest.models.Anouncement.upload_to),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.FileField(upload_to=skbrest.models.Resource.upload_to),
        ),
    ]
