# Generated by Django 2.0.6 on 2018-06-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skbrest', '0003_auto_20180613_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='ressources',
            new_name='resources',
        ),
    ]
