# Generated by Django 2.0.6 on 2018-06-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skbrest', '0004_auto_20180613_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='size',
        ),
    ]
