# Generated by Django 2.0.6 on 2018-06-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180620_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
    ]
