# Generated by Django 2.0.6 on 2018-06-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180620_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
        ),
    ]
