# Generated by Django 2.0.6 on 2018-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180621_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='post',
            name='childs',
            field=models.ManyToManyField(blank=True, to='api.Post'),
        ),
    ]
